Task 5
Xelsoid/NodeJS-practical-tasks pull request #5
Opened 2023-09-30 16:44 UTC by Xelsoid

2023-10-17 06:15 UTC, ShaxxKh requested changes
Why do you use .mjs everywhere?

2023-10-17 06:15 UTC, ShaxxKh commented on api/getUsers.mjs
> +export const getUsers = async (req, res) => {
you combined two endpoints into one, it will work for sure, but in order to keep it easy to follow and avoid more complications in the future better divide it into two endpoints `getUsers` and `getUserById`

2023-10-17 06:15 UTC, ShaxxKh commented on api/index.mjs
> +  if(pathURL === URLS.UPDATE_USER && req.method === "PUT") {
the task asks for _partial_ update and PATCH used for that, when you use PUT you must pass all properties of user, whereas for PATCH you can pass only the properties that you want to update

2023-10-17 06:15 UTC, ShaxxKh commented on api/createUsers.mjs
> +      storage = [...userData];
do you actually need spread here?

2023-10-17 06:15 UTC, ShaxxKh commented on api/createUsers.mjs
> +    returnSuccessResult(res, 'User saved')
let's use 201 code for create

2023-10-23 15:08 UTC, Xelsoid commented on api/getUsers.mjs
> +export const getUsers = async (req, res) => {
good point, splitted

2023-10-23 15:10 UTC, Xelsoid commented on api/createUsers.mjs
> +      storage = [...userData];
perhaps this remains due to the removed logic

2023-10-23 15:13 UTC, Xelsoid commented on api/index.mjs
> +  if(pathURL === URLS.UPDATE_USER && req.method === "PUT") {
ty, calls updated

2023-10-23 15:14 UTC, Xelsoid commented on api/createUsers.mjs
> +    returnSuccessResult(res, 'User saved')
updated

2023-10-23 15:17 UTC, Xelsoid commented
Hello @ShaxxKh 
I used .mjs file extension to be able to use es6 modules instead of commonJs

2023-10-30 16:41 UTC, ShaxxKh commented
@Xelsoid actually setting `"type": "module"` should have solved that

2023-10-30 16:41 UTC, ShaxxKh approved these changes

2023-10-30 16:44 UTC, Xelsoid commented
> @Xelsoid actually setting `"type": "module"` should have solved that

hmm, let me try to rename extensions then

2023-11-02 11:10 UTC, merged