Task6
Xelsoid/NodeJS-practical-tasks pull request #6
Opened 2023-10-09 14:26 UTC by Xelsoid

2023-10-17 06:52 UTC, ShaxxKh requested changes

2023-10-17 06:52 UTC, ShaxxKh commented on src/controllers/cart.controller.ts
> +const app = express();
there must be a single app in `src/app.ts` file that configured for all entities (cart, order, users)

in this `controller` file you should just have the callbacks like : `async (req: Request, res: Response, next: NextFunction) => {}` for routes. So you export all your controllers, import them in `src/app.ts` and you them like: `app.get('CART_ENDPOINTS.PROFILE_CART', getCart)`

2023-10-17 06:52 UTC, ShaxxKh commented on src/controllers/cart.controller.ts
> +    if(!userId) {
move this and the check below to separate `auth.ts` file

2023-10-17 06:52 UTC, ShaxxKh commented on src/controllers/cart.controller.ts
> +        "error": null
this is not actually necessary

2023-10-17 06:52 UTC, ShaxxKh commented on src/controllers/index.controller.ts
> +import express from 'express';
remove this file

2023-10-23 15:22 UTC, Xelsoid commented on src/controllers/cart.controller.ts
> +const app = express();
done, really helpful advice

2023-10-23 15:38 UTC, Xelsoid commented on src/controllers/cart.controller.ts
> +    if(!userId) {
done

2023-10-23 15:39 UTC, Xelsoid commented on src/controllers/cart.controller.ts
> +        "error": null
removed

2023-10-23 15:39 UTC, Xelsoid commented on src/controllers/index.controller.ts
> +import express from 'express';
removed

2023-10-23 15:43 UTC, Xelsoid commented
> not finalized yet

finalized

2023-10-30 16:50 UTC, ShaxxKh approved these changes
good job

2023-10-30 16:53 UTC, merged